# Generated by Django 5.0.1 on 2024-02-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobscraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='admin', max_length=255),
        ),
    ]
