# Generated by Django 5.0.1 on 2024-04-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobscraper', '0006_remove_joblisting_date_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
