# Generated by Django 5.0.1 on 2024-04-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobscraper', '0011_joblisting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='keyword',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=255),
        ),
    ]
