# Generated by Django 5.0.1 on 2024-05-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobscraper', '0014_joblisting_data_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='url',
            field=models.CharField(default='', max_length=1024, unique=True),
        ),
    ]
