# Generated by Django 5.0.1 on 2024-04-09 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_joblisting_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='location',
        ),
    ]
