# Generated by Django 5.0.1 on 2024-04-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_joblisting_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
