# Generated by Django 5.0.1 on 2024-04-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_joblisting_keyword_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='url',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
